import { Alert, Platform } from 'react-native';
import * as FileSystem from 'expo-file-system/legacy';
import * as MediaLibrary from 'expo-media-library';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { AttendanceRecord, Client, ProgressRecord } from '../models/types';
import { calculateBMI } from './bmrEngine';

const escapeHtml = (value: any) => String(value ?? '')
  .replace(/&/g, '&amp;')
  .replace(/</g, '&lt;')
  .replace(/>/g, '&gt;')
  .replace(/"/g, '&quot;')
  .replace(/'/g, '&#39;');

const formatDate = (value?: string, locale = 'en-GB') => {
  if (!value) return 'N/A';
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return 'N/A';
  return date.toLocaleDateString(locale, { day: 'numeric', month: 'short', year: 'numeric' });
};

type PdfLabels = {
  generated: string;
  dateLocale: string;
  generatedBy: string;
  client: string;
  name: string;
  goal: string;
  ageGender: string;
  height: string;
  latestWeight: string;
  targetWeight: string;
  healthyRange: string;
  estimatedTime: string;
  attendance: string;
  sessionsTracked: string;
  progressHistory: string;
  date: string;
  weight: string;
  notes: string;
  noProgressRecords: string;
  reportSummary: string;
  clientProgressReport: string;
  mealPlan: string;
  dailyCalories: string;
  water: string;
  type: string;
  ingredient: string;
  portion: string;
  baseCalories: string;
  protein: string;
  carbs: string;
  veggieFruit: string;
  mealTotals: string;
  calories: string;
  fats: string;
  noteWater: string;
  noteSleep: string;
  noteExercise: string;
};

type ProgressPdfClient = Omit<Client, 'goal'> & { goal: string };

const defaultPdfLabels: PdfLabels = {
  generated: 'Generated',
  dateLocale: 'en-GB',
  generatedBy: 'Generated by ClientTracking',
  client: 'Client',
  name: 'Name',
  goal: 'Goal',
  ageGender: 'Age / Gender',
  height: 'Height',
  latestWeight: 'Latest weight',
  targetWeight: 'Target weight',
  healthyRange: 'Healthy range',
  estimatedTime: 'Estimated time',
  attendance: 'Attendance',
  sessionsTracked: 'Sessions tracked',
  progressHistory: 'Progress History',
  date: 'Date',
  weight: 'Weight',
  notes: 'Notes',
  noProgressRecords: 'No progress records yet.',
  reportSummary: 'Summary',
  clientProgressReport: 'Client Progress Report',
  mealPlan: 'Meal Plan',
  dailyCalories: 'Daily calories',
  water: 'Water',
  type: 'Type',
  ingredient: 'Ingredient',
  portion: 'Portion',
  baseCalories: 'Base calories',
  protein: 'Protein',
  carbs: 'Carbs',
  veggieFruit: 'Veggie/Fruit',
  mealTotals: 'Meal Totals',
  calories: 'Calories',
  fats: 'Fats',
  noteWater: 'Drink water throughout the day.',
  noteSleep: 'Sleep 7-8 hours when possible.',
  noteExercise: 'Adjust portions with your trainer if weight changes too fast or too slow.',
};

const getPdfLabels = (labels?: Partial<PdfLabels>): PdfLabels => ({ ...defaultPdfLabels, ...labels });

export const getSafeFileName = (name?: string, suffix = 'report') => {
  const safeName = String(name || 'client')
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '') || 'client';
  const safeSuffix = suffix.replace(/[^a-z0-9-]+/gi, '-').replace(/^-+|-+$/g, '') || 'report';
  return `${safeName}-${safeSuffix}`;
};

const reportShell = (title: string, body: string, labels = defaultPdfLabels) => `
  <!doctype html>
  <html>
    <head>
      <meta charset="utf-8" />
      <style>
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; color: #171717; padding: 28px; }
        .header { border-bottom: 3px solid #ccff00; padding-bottom: 14px; margin-bottom: 20px; }
        h1 { font-size: 26px; margin: 0 0 6px; }
        h2 { font-size: 17px; margin: 22px 0 10px; }
        .muted { color: #666; font-size: 12px; }
        .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; margin: 14px 0; }
        .box { border: 1px solid #ddd; border-radius: 8px; padding: 12px; }
        .label { color: #666; font-size: 11px; text-transform: uppercase; margin-bottom: 4px; }
        .value { font-size: 16px; font-weight: 700; }
        table { width: 100%; border-collapse: collapse; margin-top: 8px; }
        th { background: #f1f1f1; text-align: left; font-size: 12px; }
        th, td { border: 1px solid #ddd; padding: 8px; font-size: 12px; vertical-align: top; }
        ul { padding-left: 18px; }
        li { margin-bottom: 6px; }
        .footer { margin-top: 28px; padding-top: 12px; border-top: 1px solid #ddd; color: #777; font-size: 11px; }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>${escapeHtml(title)}</h1>
        <div class="muted">${escapeHtml(labels.generated)} ${formatDate(new Date().toISOString(), labels.dateLocale)}</div>
      </div>
      ${body}
      <div class="footer">${escapeHtml(labels.generatedBy)}</div>
    </body>
  </html>
`;

const createPdfFile = async (html: string, fileName: string) => {
  const { uri } = await Print.printToFileAsync({ html, base64: false });
  const namedUri = `${FileSystem.cacheDirectory}${fileName}`;
  await FileSystem.deleteAsync(namedUri, { idempotent: true });
  await FileSystem.copyAsync({ from: uri, to: namedUri });
  return namedUri;
};

const savePdfToPhone = async (html: string, fileName: string) => {
  try {
    const namedUri = await createPdfFile(html, fileName);

    if (Platform.OS === 'android' && FileSystem.StorageAccessFramework) {
      const permissions = await FileSystem.StorageAccessFramework.requestDirectoryPermissionsAsync();
      if (!permissions.granted) return;

      const base64 = await FileSystem.readAsStringAsync(namedUri, { encoding: FileSystem.EncodingType.Base64 });
      const destinationUri = await FileSystem.StorageAccessFramework.createFileAsync(
        permissions.directoryUri,
        fileName,
        'application/pdf'
      );
      await FileSystem.writeAsStringAsync(destinationUri, base64, { encoding: FileSystem.EncodingType.Base64 });
      Alert.alert('Saved', `${fileName} saved to your selected folder.`);
      return;
    }

    const canShare = await Sharing.isAvailableAsync();
    if (canShare) {
      await Sharing.shareAsync(namedUri, {
        mimeType: 'application/pdf',
        dialogTitle: `Save ${fileName}`,
        UTI: 'com.adobe.pdf',
      });
      return;
    }

    Alert.alert('PDF created', `PDF saved at ${namedUri}`);
  } catch (error: any) {
    Alert.alert('PDF Error', error.message || 'Failed to save PDF.');
  }
};

const sharePdf = async (html: string, fileName: string) => {
  try {
    const namedUri = await createPdfFile(html, fileName);
    const canShare = await Sharing.isAvailableAsync();
    if (!canShare) {
      Alert.alert('PDF created', `PDF saved at ${namedUri}`);
      return;
    }
    await Sharing.shareAsync(namedUri, {
      mimeType: 'application/pdf',
      dialogTitle: fileName,
      UTI: 'com.adobe.pdf',
    });
  } catch (error: any) {
    Alert.alert('PDF Error', error.message || 'Failed to create PDF.');
  }
};

export const saveImageFile = async (uri: string, fileName: string) => {
  try {
    const namedUri = `${FileSystem.cacheDirectory}${fileName}`;
    await FileSystem.deleteAsync(namedUri, { idempotent: true });
    await FileSystem.copyAsync({ from: uri, to: namedUri });
    const { status } = await MediaLibrary.requestPermissionsAsync(true);
    if (status !== 'granted') {
      Alert.alert('Permission needed', 'Please allow photo access to save the image.');
      return;
    }
    await MediaLibrary.saveToLibraryAsync(namedUri);
    Alert.alert('Saved', `${fileName} saved to your photos.`);
  } catch (error: any) {
    Alert.alert('Image Error', error.message || 'Failed to save image.');
  }
};

export const shareImageFile = async (uri: string, fileName: string) => {
  try {
    const namedUri = `${FileSystem.cacheDirectory}${fileName}`;
    await FileSystem.deleteAsync(namedUri, { idempotent: true });
    await FileSystem.copyAsync({ from: uri, to: namedUri });
    const canShare = await Sharing.isAvailableAsync();
    if (!canShare) {
      Alert.alert('Image created', `Image saved at ${namedUri}`);
      return;
    }
    await Sharing.shareAsync(namedUri, {
      mimeType: 'image/jpeg',
      dialogTitle: fileName,
      UTI: 'public.jpeg',
    });
  } catch (error: any) {
    Alert.alert('Image Error', error.message || 'Failed to create image.');
  }
};

export const shareMealPlanPdf = async (params: {
  client: Partial<Client>;
  mealName: string;
  dailyCalories: number;
  waterLiters: string;
  proteinItem: any;
  carbItem: any;
  veggieItem: any;
  proteinGrams: number;
  carbGrams: number;
  veggieGrams: number;
  totalProtein: number;
  totalCarbs: number;
  totalFats: number;
  totalMealCals: number;
  labels?: Partial<PdfLabels>;
}) => {
  const labels = getPdfLabels(params.labels);
  const body = `
    <h2>${escapeHtml(labels.client)}</h2>
    <div class="grid">
      <div class="box"><div class="label">${escapeHtml(labels.name)}</div><div class="value">${escapeHtml(params.client.name || labels.client)}</div></div>
      <div class="box"><div class="label">${escapeHtml(labels.goal)}</div><div class="value">${escapeHtml(params.client.goal || 'N/A')}</div></div>
      <div class="box"><div class="label">${escapeHtml(labels.dailyCalories)}</div><div class="value">${params.dailyCalories} kcal</div></div>
      <div class="box"><div class="label">${escapeHtml(labels.water)}</div><div class="value">${escapeHtml(params.waterLiters)} L</div></div>
    </div>

    <h2>${escapeHtml(labels.mealPlan)}: ${escapeHtml(params.mealName)}</h2>
    <table>
      <tr><th>${escapeHtml(labels.type)}</th><th>${escapeHtml(labels.ingredient)}</th><th>${escapeHtml(labels.portion)}</th><th>${escapeHtml(labels.baseCalories)}</th></tr>
      <tr><td>${escapeHtml(labels.protein)}</td><td>${escapeHtml(params.proteinItem?.name || 'N/A')}</td><td>${params.proteinGrams}g</td><td>${Math.round(params.proteinItem?.calsBase || 0)} kcal / 100g</td></tr>
      <tr><td>${escapeHtml(labels.carbs)}</td><td>${escapeHtml(params.carbItem?.name || 'N/A')}</td><td>${params.carbGrams}g</td><td>${Math.round(params.carbItem?.calsBase || 0)} kcal / 100g</td></tr>
      <tr><td>${escapeHtml(labels.veggieFruit)}</td><td>${escapeHtml(params.veggieItem?.name || 'N/A')}</td><td>${params.veggieGrams}g</td><td>${Math.round(params.veggieItem?.calsBase || 0)} kcal / 100g</td></tr>
    </table>

    <h2>${escapeHtml(labels.mealTotals)}</h2>
    <div class="grid">
      <div class="box"><div class="label">${escapeHtml(labels.calories)}</div><div class="value">${params.totalMealCals} kcal</div></div>
      <div class="box"><div class="label">${escapeHtml(labels.protein)}</div><div class="value">${params.totalProtein}g</div></div>
      <div class="box"><div class="label">${escapeHtml(labels.carbs)}</div><div class="value">${params.totalCarbs}g</div></div>
      <div class="box"><div class="label">${escapeHtml(labels.fats)}</div><div class="value">${params.totalFats}g</div></div>
    </div>

    <h2>${escapeHtml(labels.notes)}</h2>
    <ul>
      <li>${escapeHtml(labels.noteWater)}</li>
      <li>${escapeHtml(labels.noteSleep)}</li>
      <li>${escapeHtml(labels.noteExercise)}</li>
    </ul>
  `;

  const fileName = `${getSafeFileName(params.client.name, 'meal-plan')}.pdf`;
  await sharePdf(reportShell(labels.mealPlan, body, labels), fileName);
};

export const saveMealPlanPdf = async (params: Parameters<typeof shareMealPlanPdf>[0]) => {
  const labels = getPdfLabels(params.labels);
  const body = `
    <h2>${escapeHtml(labels.client)}</h2>
    <div class="grid">
      <div class="box"><div class="label">${escapeHtml(labels.name)}</div><div class="value">${escapeHtml(params.client.name || labels.client)}</div></div>
      <div class="box"><div class="label">${escapeHtml(labels.goal)}</div><div class="value">${escapeHtml(params.client.goal || 'N/A')}</div></div>
      <div class="box"><div class="label">${escapeHtml(labels.dailyCalories)}</div><div class="value">${params.dailyCalories} kcal</div></div>
      <div class="box"><div class="label">${escapeHtml(labels.water)}</div><div class="value">${escapeHtml(params.waterLiters)} L</div></div>
    </div>

    <h2>${escapeHtml(labels.mealPlan)}: ${escapeHtml(params.mealName)}</h2>
    <table>
      <tr><th>${escapeHtml(labels.type)}</th><th>${escapeHtml(labels.ingredient)}</th><th>${escapeHtml(labels.portion)}</th><th>${escapeHtml(labels.baseCalories)}</th></tr>
      <tr><td>${escapeHtml(labels.protein)}</td><td>${escapeHtml(params.proteinItem?.name || 'N/A')}</td><td>${params.proteinGrams}g</td><td>${Math.round(params.proteinItem?.calsBase || 0)} kcal / 100g</td></tr>
      <tr><td>${escapeHtml(labels.carbs)}</td><td>${escapeHtml(params.carbItem?.name || 'N/A')}</td><td>${params.carbGrams}g</td><td>${Math.round(params.carbItem?.calsBase || 0)} kcal / 100g</td></tr>
      <tr><td>${escapeHtml(labels.veggieFruit)}</td><td>${escapeHtml(params.veggieItem?.name || 'N/A')}</td><td>${params.veggieGrams}g</td><td>${Math.round(params.veggieItem?.calsBase || 0)} kcal / 100g</td></tr>
    </table>

    <h2>${escapeHtml(labels.mealTotals)}</h2>
    <div class="grid">
      <div class="box"><div class="label">${escapeHtml(labels.calories)}</div><div class="value">${params.totalMealCals} kcal</div></div>
      <div class="box"><div class="label">${escapeHtml(labels.protein)}</div><div class="value">${params.totalProtein}g</div></div>
      <div class="box"><div class="label">${escapeHtml(labels.carbs)}</div><div class="value">${params.totalCarbs}g</div></div>
      <div class="box"><div class="label">${escapeHtml(labels.fats)}</div><div class="value">${params.totalFats}g</div></div>
    </div>

    <h2>${escapeHtml(labels.notes)}</h2>
    <ul>
      <li>${escapeHtml(labels.noteWater)}</li>
      <li>${escapeHtml(labels.noteSleep)}</li>
      <li>${escapeHtml(labels.noteExercise)}</li>
    </ul>
  `;
  const fileName = `${getSafeFileName(params.client.name, 'meal-plan')}.pdf`;
  await savePdfToPhone(reportShell(labels.mealPlan, body, labels), fileName);
};

export const shareClientProgressPdf = async (params: {
  client: ProgressPdfClient;
  records: ProgressRecord[];
  attendance: AttendanceRecord[];
  targetWeight: number;
  healthyMin: number;
  healthyMax: number;
  estimatedWeeks: string;
  labels?: Partial<PdfLabels>;
}) => {
  const labels = getPdfLabels(params.labels);
  const latest = params.records[0];
  const attendedCount = params.attendance.filter(item => item.attended).length;
  const rows = params.records.slice(0, 20).map(record => `
    <tr>
      <td>${formatDate(record.date, labels.dateLocale)}</td>
      <td>${record.currentWeightKG} kg</td>
      <td>${record.bmi || calculateBMI(record.currentWeightKG, params.client.heightCM)}</td>
      <td>${escapeHtml(record.notes || '')}</td>
    </tr>
  `).join('');

  const body = `
    <h2>${escapeHtml(labels.reportSummary)}</h2>
    <div class="grid">
      <div class="box"><div class="label">${escapeHtml(labels.name)}</div><div class="value">${escapeHtml(params.client.name)}</div></div>
      <div class="box"><div class="label">${escapeHtml(labels.goal)}</div><div class="value">${escapeHtml(params.client.goal)}</div></div>
      <div class="box"><div class="label">${escapeHtml(labels.ageGender)}</div><div class="value">${params.client.age} / ${escapeHtml(params.client.gender)}</div></div>
      <div class="box"><div class="label">${escapeHtml(labels.height)}</div><div class="value">${params.client.heightCM} cm</div></div>
      <div class="box"><div class="label">${escapeHtml(labels.latestWeight)}</div><div class="value">${latest ? `${latest.currentWeightKG} kg` : 'N/A'}</div></div>
      <div class="box"><div class="label">${escapeHtml(labels.targetWeight)}</div><div class="value">${params.targetWeight} kg</div></div>
      <div class="box"><div class="label">${escapeHtml(labels.healthyRange)}</div><div class="value">${params.healthyMin} - ${params.healthyMax} kg</div></div>
      <div class="box"><div class="label">${escapeHtml(labels.estimatedTime)}</div><div class="value">${escapeHtml(params.estimatedWeeks)}</div></div>
    </div>

    <h2>${escapeHtml(labels.attendance)}</h2>
    <div class="box"><div class="label">${escapeHtml(labels.sessionsTracked)}</div><div class="value">${attendedCount}</div></div>

    <h2>${escapeHtml(labels.progressHistory)}</h2>
    <table>
      <tr><th>${escapeHtml(labels.date)}</th><th>${escapeHtml(labels.weight)}</th><th>BMI</th><th>${escapeHtml(labels.notes)}</th></tr>
      ${rows || `<tr><td colspan="4">${escapeHtml(labels.noProgressRecords)}</td></tr>`}
    </table>
  `;

  const fileName = `${getSafeFileName(params.client.name, 'progress-report')}.pdf`;
  await sharePdf(reportShell(labels.clientProgressReport, body, labels), fileName);
};

export const saveClientProgressPdf = async (params: Parameters<typeof shareClientProgressPdf>[0]) => {
  const labels = getPdfLabels(params.labels);
  const latest = params.records[0];
  const attendedCount = params.attendance.filter(item => item.attended).length;
  const rows = params.records.slice(0, 20).map(record => `
    <tr>
      <td>${formatDate(record.date, labels.dateLocale)}</td>
      <td>${record.currentWeightKG} kg</td>
      <td>${record.bmi || calculateBMI(record.currentWeightKG, params.client.heightCM)}</td>
      <td>${escapeHtml(record.notes || '')}</td>
    </tr>
  `).join('');

  const body = `
    <h2>${escapeHtml(labels.reportSummary)}</h2>
    <div class="grid">
      <div class="box"><div class="label">${escapeHtml(labels.name)}</div><div class="value">${escapeHtml(params.client.name)}</div></div>
      <div class="box"><div class="label">${escapeHtml(labels.goal)}</div><div class="value">${escapeHtml(params.client.goal)}</div></div>
      <div class="box"><div class="label">${escapeHtml(labels.ageGender)}</div><div class="value">${params.client.age} / ${escapeHtml(params.client.gender)}</div></div>
      <div class="box"><div class="label">${escapeHtml(labels.height)}</div><div class="value">${params.client.heightCM} cm</div></div>
      <div class="box"><div class="label">${escapeHtml(labels.latestWeight)}</div><div class="value">${latest ? `${latest.currentWeightKG} kg` : 'N/A'}</div></div>
      <div class="box"><div class="label">${escapeHtml(labels.targetWeight)}</div><div class="value">${params.targetWeight} kg</div></div>
      <div class="box"><div class="label">${escapeHtml(labels.healthyRange)}</div><div class="value">${params.healthyMin} - ${params.healthyMax} kg</div></div>
      <div class="box"><div class="label">${escapeHtml(labels.estimatedTime)}</div><div class="value">${escapeHtml(params.estimatedWeeks)}</div></div>
    </div>

    <h2>${escapeHtml(labels.attendance)}</h2>
    <div class="box"><div class="label">${escapeHtml(labels.sessionsTracked)}</div><div class="value">${attendedCount}</div></div>

    <h2>${escapeHtml(labels.progressHistory)}</h2>
    <table>
      <tr><th>${escapeHtml(labels.date)}</th><th>${escapeHtml(labels.weight)}</th><th>BMI</th><th>${escapeHtml(labels.notes)}</th></tr>
      ${rows || `<tr><td colspan="4">${escapeHtml(labels.noProgressRecords)}</td></tr>`}
    </table>
  `;
  const fileName = `${getSafeFileName(params.client.name, 'progress-report')}.pdf`;
  await savePdfToPhone(reportShell(labels.clientProgressReport, body, labels), fileName);
};
