import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import * as FileSystem from 'expo-file-system/legacy';
import { Platform } from 'react-native';
import { saveImageToGallery } from './saveImageToGallery';

type Branding = {
  gymLogo?: string;
  gymName?: string;
  trainerName?: string;
};

const defaultPdfLabels = {
  generated: 'Generated',
  preparedFor: 'Prepared for',
  date: 'Date',
  generatedBy: 'Generated by ClientTracking',
  mealPlan: 'Meal Plan',
  progressReport: 'Progress Report',
  summary: 'Summary',
  change: 'Change',
  weight: 'Weight',
  category: 'Category',
  ingredient: 'Ingredient',
  portion: 'Portion',
  dailyTargets: 'Daily Targets',
  nutritionTarget: 'nutrition target',
  dateLocale: 'en-US',
};

const escapeHtml = (unsafe: string) => {
  return unsafe
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
};

const formatDate = (dateStr: string, locale = 'en-US') => {
  try {
    return new Date(dateStr).toLocaleDateString(locale, {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });
  } catch (e) {
    return dateStr;
  }
};

export const getSafeFileName = (name: string, prefix: string) => {
  return `${prefix}_${name.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_${Date.now()}`;
};

export const shareImageFile = async (uri: string, fileName: string) => {
  if (!(await Sharing.isAvailableAsync())) {
    throw new Error('Sharing is not available on this device');
  }
  const newPath = FileSystem.cacheDirectory + fileName;
  await FileSystem.copyAsync({ from: uri, to: newPath });
  await Sharing.shareAsync(newPath);
};

export const saveImageFile = async (uri: string, fileName: string) => {
  // Use the robust MediaLibrary-based saver for a better experience
  return await saveImageToGallery(uri);
};

const reportShell = (title: string, body: string, labels = defaultPdfLabels, branding?: Branding) => `
  <html>
    <head>
      <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no" />
      <style>
        body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; padding: 40px; color: #172033; line-height: 1.4; }
        .header { border-bottom: 2px solid #d9e7f7; padding-bottom: 20px; margin-bottom: 30px; position: relative; }
        .branding-header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 10px; }
        .branding-logo { max-height: 60px; max-width: 150px; object-fit: contain; }
        .branding-text { font-size: 12px; color: #667085; margin-top: 5px; font-style: italic; }
        .gym-highlight { color: #2b6cb0; font-weight: bold; font-style: normal; font-size: 14px; }
        h1 { margin: 0; color: #172033; font-size: 28px; font-weight: bold; }
        .muted { color: #667085; font-size: 14px; margin-top: 5px; }
        .section { margin-bottom: 30px; }
        .section-title { font-size: 18px; font-weight: bold; margin-bottom: 15px; border-left: 4px solid #2b6cb0; padding-left: 12px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; border: 1px solid #d0d7de; border-radius: 8px; overflow: hidden; }
        th { background-color: #f6f8fa; text-align: left; padding: 12px; font-size: 12px; text-transform: uppercase; color: #667085; border-bottom: 1px solid #d0d7de; }
        td { padding: 12px; font-size: 14px; border-bottom: 1px solid #e5e7eb; }
        .footer { margin-top: 50px; padding-top: 20px; border-top: 1px solid #e5e7eb; text-align: right; color: #98a2b3; font-size: 12px; }
        .highlight-box { background-color: #f8fafc; padding: 20px; border-radius: 8px; border: 1px solid #d9e7f7; display: flex; flex-wrap: wrap; gap: 20px; margin-bottom: 25px; }
        .metric { flex: 1; min-width: 120px; }
        .metric-label { font-size: 11px; font-weight: bold; color: #667085; text-transform: uppercase; margin-bottom: 5px; }
        .metric-value { font-size: 20px; font-weight: bold; color: #172033; }
        .profile-row { display: flex; align-items: center; gap: 20px; margin-bottom: 30px; background: #f8fafc; padding: 15px; border-left: 4px solid #2b6cb0; }
        .profile-img { width: 60px; height: 60px; border-radius: 30px; object-fit: cover; background: #eee; }
      </style>
    </head>
    <body>
      <div class="header">
        <div class="branding-header">
          <div>
            <h1>${escapeHtml(title)}</h1>
            <div class="muted">${escapeHtml(labels.generated)} ${formatDate(new Date().toISOString(), labels.dateLocale)}</div>
          </div>
          ${branding?.gymLogo ? `<img src="${branding.gymLogo}" class="branding-logo" />` : ''}
        </div>
        ${branding?.gymName || branding?.trainerName ? `
          <div class="branding-text">
            ${branding.gymName ? `<span class="gym-highlight">${escapeHtml(branding.gymName)}</span>` : ''}
            ${branding.gymName && branding.trainerName ? ' | ' : ''}
            ${branding.trainerName ? `<span>Trainer: ${escapeHtml(branding.trainerName)}</span>` : ''}
          </div>
        ` : ''}
      </div>
      ${body}
      <div class="footer">${escapeHtml(labels.generatedBy)}</div>
    </body>
  </html>
`;

const createPdfFile = async (html: string, fileName: string) => {
  const { uri } = await Print.printToFileAsync({ html, base64: false });
  const namedUri = `${FileSystem.cacheDirectory}${fileName}`;
  await FileSystem.deleteAsync(namedUri, { idempotent: true });
  await FileSystem.copyAsync({ from: uri, to: namedUri });
  return namedUri;
};

const sharePdf = async (html: string, fileName: string) => {
  const uri = await createPdfFile(html, fileName);
  if (Platform.OS === 'ios') {
    await Sharing.shareAsync(uri, { UTI: 'com.adobe.pdf', mimeType: 'application/pdf' });
  } else {
    await Sharing.shareAsync(uri, { mimeType: 'application/pdf' });
  }
};

export const shareMealPlanPdf = async (params: {
  client: any;
  meal: any;
  cals: number;
  waterLiters: number;
  proteinGrams: number;
  carbGrams: number;
  veggieGrams: number;
  labels: typeof defaultPdfLabels;
  branding?: Branding;
}) => {
  const { client, meal, cals, waterLiters, proteinGrams, carbGrams, veggieGrams, labels, branding } = params;
  const body = `
    <div class="profile-row">
      ${client.imageUri ? `<img src="${client.imageUri}" class="profile-img" />` : '<div class="profile-img"></div>'}
      <div>
        <div style="font-weight: bold; font-size: 18px;">${escapeHtml(client.name)}</div>
        <div class="muted">${escapeHtml(labels.preparedFor)}</div>
      </div>
    </div>

    <div class="section">
      <div class="section-title">${escapeHtml(labels.dailyTargets)}</div>
      <div class="highlight-box">
        <div class="metric">
          <div class="metric-label">Calories</div>
          <div class="metric-value">${cals} kcal</div>
        </div>
        <div class="metric">
          <div class="metric-label">Water</div>
          <div class="metric-value">${waterLiters} L</div>
        </div>
      </div>
    </div>

    <div class="section">
      <div class="section-title">${escapeHtml(labels.mealPlan)}</div>
      <table>
        <thead>
          <tr>
            <th>${escapeHtml(labels.category)}</th>
            <th>${escapeHtml(labels.ingredient)}</th>
            <th>${escapeHtml(labels.portion)}</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Protein</td>
            <td>${escapeHtml(meal.p?.name || 'N/A')}</td>
            <td>${proteinGrams}g</td>
          </tr>
          <tr>
            <td>Carbs</td>
            <td>${escapeHtml(meal.c?.name || 'N/A')}</td>
            <td>${carbGrams}g</td>
          </tr>
          <tr>
            <td>Veggie/Fruit</td>
            <td>${escapeHtml(meal.v?.name || 'N/A')}</td>
            <td>${veggieGrams}g</td>
          </tr>
        </tbody>
      </table>
    </div>
  `;

  const fileName = `MealPlan_${client.name.replace(/\s+/g, '_')}.pdf`;
  await sharePdf(reportShell(labels.mealPlan, body, labels, branding), fileName);
};

export const saveMealPlanPdf = async (params: {
  client: any;
  meal: any;
  cals: number;
  waterLiters: number;
  proteinGrams: number;
  carbGrams: number;
  veggieGrams: number;
  labels: typeof defaultPdfLabels;
  branding?: Branding;
}) => {
  // Same logic as share but could be different if we had a dedicated save action
  await shareMealPlanPdf(params);
};

export const shareClientProgressPdf = async (params: {
  client: any;
  records: any[];
  attendance: any[];
  targetWeight: string;
  healthyMin: string;
  healthyMax: string;
  estimatedWeeks: string;
  labels: typeof defaultPdfLabels;
  branding?: Branding;
}) => {
  const { client, records, attendance, targetWeight, healthyMin, healthyMax, estimatedWeeks, labels, branding } = params;
  
  const recordsHtml = records.map(r => `
    <tr>
      <td>${formatDate(r.date, labels.dateLocale)}</td>
      <td>${r.currentWeightKG} kg</td>
      <td>${r.bmi.toFixed(1)}</td>
      <td>${escapeHtml(r.notes || '-')}</td>
    </tr>
  `).join('');

  const body = `
    <div class="profile-row">
      ${client.imageUri ? `<img src="${client.imageUri}" class="profile-img" />` : '<div class="profile-img"></div>'}
      <div>
        <div style="font-weight: bold; font-size: 18px;">${escapeHtml(client.name)}</div>
        <div class="muted">${escapeHtml(client.goal)} | ${client.heightCM} cm</div>
      </div>
    </div>

    <div class="section">
      <div class="section-title">${escapeHtml(labels.summary)}</div>
      <div class="highlight-box">
        <div class="metric">
          <div class="metric-label">Target Weight</div>
          <div class="metric-value">${targetWeight} kg</div>
        </div>
        <div class="metric">
          <div class="metric-label">Estimated Time</div>
          <div class="metric-value">${estimatedWeeks} weeks</div>
        </div>
        <div class="metric">
          <div class="metric-label">Healthy Range</div>
          <div class="metric-value">${healthyMin}-${healthyMax} kg</div>
        </div>
      </div>
    </div>

    <div class="section">
      <div class="section-title">History</div>
      <table>
        <thead>
          <tr>
            <th>${escapeHtml(labels.date)}</th>
            <th>${escapeHtml(labels.weight)}</th>
            <th>BMI</th>
            <th>Notes</th>
          </tr>
        </thead>
        <tbody>
          ${recordsHtml || `<tr><td colspan="4" style="text-align:center">No records found</td></tr>`}
        </tbody>
      </table>
    </div>
  `;

  const fileName = `ProgressReport_${client.name.replace(/\s+/g, '_')}.pdf`;
  await sharePdf(reportShell(labels.progressReport, body, labels, branding), fileName);
};

export const saveClientProgressPdf = async (params: any) => {
  await shareClientProgressPdf(params);
};
